# Meta
title: Lorem
description: >
  Ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

# Tech
sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
